### PR TITLE
recode

### PR DESCRIPTION
**Pull request by CheaterTim**
a complete recode of the CU website
old
new

### CODE REVIEW

**Comment by Reasonlesss** [comment]
I am sorry, but I'm not that big of a fan, website changes way too much anyway. Also the html isn't messed up 🙄

**Comment by AstroSquared** [comment]
> I am sorry, but I'm not that big of a fan, website changes way too much anyway. Also the html isn't messed up 🙄

why do you want the html messed up

**Comment by CheaterTim** [comment]
> I am sorry, but I'm not that big of a fan, website changes way too much anyway. Also the html isn't messed up 🙄

its a lot better than the current page in my opinion

**Comment by TechStreetDev** [comment]
> its a lot better than the current page in my opinion

I also dislike the webpage

**Comment by CheaterTim** [comment]
screenshot
image

**Pull request closed without merging**
