### PR TITLE
Website Remake

### PR DESCRIPTION
**Pull request by AstroSquared**
I remade the website. also sorry if this pr is broken i suck at pull requests

Preview at: https://squaredstudios-mc.github.io/codeutilities.github.io/

**Features**
* Faster load time
* Mobile support
* Similar to old website
* Made in Bootstrap

If needed, i can make the indentation messed up when everything else is good.

### CODE REVIEW

**Review by DaMan56100 — CHANGES_REQUESTED** [review]
why do you edit readme & some random jars?

**Comment by GeorgeRNG** [comment]
all the jars got smaller

**Comment by CheaterTim** [comment]
> all the jars got smaller

thats kinda sus

**Comment by AstroSquared** [comment]
> why do you edit readme & some random jars?

i can change the readme back if you want
i deleted the jars cuz the links in the current website just has the link to the releases page



> all the jars got smaller

that means i deleted them

**Pull request closed without merging**
